services:

  backend:
    image: mfmanu05/lgtm-backend:latest
     
    container_name: lgtm-backend

    restart: unless-stopped

    ports:
      - "3000:3000"

    networks:
      - lgtm-network

  node-exporter:
    image: prom/node-exporter:latest

    container_name: node-exporter

    ports:
      - "9100:9100"
    
    command:
      - --path.rootfs=/

    pid: host

    restart: unless-stopped

    networks:
      - lgtm-network

  tempo:
    image: grafana/tempo:2.5.0
    container_name: tempo

    command:
      - "-config.file=/etc/tempo/tempo.yaml"

    volumes:
      - ./observability/tempo/tempo.yaml:/etc/tempo/tempo.yaml:ro
      - tempo-data:/var/tempo

    restart: unless-stopped

    ports:
      - "3200:3200"

    networks:
      - lgtm-network


  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest

    container_name: cadvisor

    command:
      - --docker_only=true

    ports:
      - "8081:8080"

    privileged: true

    devices:
      - /dev/kmsg

    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro

    restart: unless-stopped

    networks:
      - lgtm-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus

    restart: unless-stopped

    ports:
      - "9090:9090"

    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    command:
      - --config.file=/etc/prometheus/prometheus.yml

    networks:
      - lgtm-network


  


  frontend:
    image: mfmanu05/lgtm-frontend:latest


    container_name: lgtm-frontend

    restart: unless-stopped

    ports:
      - "80:80"

    depends_on:
      - backend

    networks:
      - lgtm-network



  loki:

    image: grafana/loki:3.0.0

    container_name: loki

    restart: unless-stopped

    ports:
      - "3100:3100"

    volumes:
      - ./observability/loki/loki.yaml:/etc/loki/loki.yaml

    command:
      - -config.file=/etc/loki/loki.yaml

    networks:
      - lgtm-network



  alloy:

    image: grafana/alloy:latest

    container_name: alloy

    restart: unless-stopped

    ports:
      - "4317:4317"
      - "4318:4318"

    volumes:
      - ./observability/alloy/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock

    command:
      - run
      - /etc/alloy/config.alloy

    depends_on:
      - loki

    networks:
      - lgtm-network



  grafana:
    environment:
      - GF_SERVER_DOMAIN=grafana.mfmanu.shop
      - GF_SERVER_ROOT_URL=http://grafana.mussulo30.shop

    image: grafana/grafana:latest

    container_name: grafana

    restart: unless-stopped

    expose:
      - "3000"

    volumes:
      - grafana-storage:/var/lib/grafana

    depends_on:
      - loki
      - prometheus

    networks:
      - lgtm-network



networks:

  lgtm-network:
    driver: bridge



volumes:

  grafana-storage:

  tempo-data:
