name: CI - LGTM Observability Platform


on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:

  build:

    name: Build Docker Images

    runs-on: ubuntu-latest


    steps:

      - name: Checkout repository
        uses: actions/checkout@v4



      - name: Docker Build Backend
        run: |
          docker build \
          -t lgtm-backend \
          ./app/backend



      - name: Docker Build Frontend
        run: |
          docker build \
          -t lgtm-frontend \
          ./app/frontend



      - name: Validate Docker Compose
        run: |
          docker compose config
