name: CI - LGTM Observability Platform

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:

  build-and-test:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout repository
        uses: actions/checkout@v4



      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22



      - name: Install backend dependencies
        working-directory: app/backend
        run: npm ci



      - name: Install frontend dependencies
        working-directory: app/frontend
        run: npm ci



      - name: Build Docker images
        run: |
          docker compose build



      - name: Start stack
        run: |
          docker compose up -d


      - name: Wait containers
        run: |
          sleep 20


      - name: Check running containers
        run: |
          docker ps



      - name: Test backend through nginx
        run: |
          curl --fail http://localhost/api/generate



      - name: Test frontend
        run: |
          curl --fail http://localhost


      - name: Show logs on failure
        if: failure()
        run: |
          docker compose logs



      - name: Shutdown
        if: always()
        run: |
          docker compose down
